title: Carteles accesibles
description: Sitio de publicación de texto alternativo generado automáticamente, revisado y corregidos manualmente.
author: 
  name: Dirección de Accesibilidad, Facultad de Informática, UNLP
theme: minima
skin: auto
minima:
  nav_pages:
    - lista-carteles.md
    - contacto.md
markdown: kramdown
