baseurl: /carteles-accesibles
url: https://mikrod-info.github.io

title: Carteles accesibles
description: Plataforma de texto alternativo de carteles educativos, accesible mediante QR y lectores de pantalla.
author: Dirección de Accesibilidad, Facultad de Informática, UNLP
favicon: /assets/icons/favicon.svg

theme: minima
skin: auto
markdown: kramdown

collections:
  carteles:
    output: true
    permalink: /carteles/:name/

defaults:
  - scope:
      type: carteles
    values:
      layout: default

header_pages:
  - index.md
  - carteles/index.md
  - contacto.md
